on: [push, pull_request]

name: Continuous integration

jobs:
  ci-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv6m-none-eabi
      - name: Install gcc
        run: sudo apt-get update && sudo apt-get install gcc-arm-none-eabi
      - name: Run CI script for thumbv6m-none-eabi
        run: bash ./check-blobs.sh
